### ISSUE TITLE
missing bot.py file

### ISSUE THREAD

**Issue by jrabensc** [kylef-archive/znc-bot#10]
Is this still supported? I think the bot.py file is missing in /bot

**Comment by kylef** [comment]
There was never a bot.py file, are you facing a specific issue. Can you elaborate on your problems?

**Comment by pawalt8** [comment]
Thanks for you answer. I tried to load the bot via "loadmod bot" and znc says "<*status> Unable to find modinfo [bot] [Unable to find module [bot]]". So i looked through the commits and found this: https://github.com/kylef/znc-bot/commit/abc2b64fcd30563fe272d3f64d4bcdaa1ecb6f97. There's a file named bot.py, to which i thought the "loadmod bot" command refered to. If this is outdated, can you tell me how to load the module?
