### ISSUE TITLE
Search of words in github issues from irc

### ISSUE THREAD

**Issue by DarthGandalf** [kylef-archive/znc-bot#7]

**Comment by jakoch** [comment]
Link to the manual:
http://developer.github.com/v3/search/#search-issues

Example for a request:
GET-Request to URL: https://api.github.com/repos/kylef/znc-bot/issues
JSON-Response object contains all issues. 
Each issue has "title" (string), "body" (string).

**Comment by kylef** [comment]
Closing since I have no interest in implementing such a feature. Please open a pull request if you would like this.
